#!/bin/sh

# Builds hlibc Docker-based test images in parallel
# (if GNU parallel is installed, otherwise sequentially),
# uploads to the public Docker Hub repository.

REPO=hlibc
PFIX=build
TODO=$(find . -type f -name "Dockerfile.*")

docker login -u ${REPO}

build ()
{
    x=${1}/${2}:$(basename ${3});
    docker build . -f ${3} -t ${x};
    docker push ${x};
}

export -f build # non-POSIX but useful

command -v parallel >/dev/null 2>&1 \
&& {
    parallel "build ${REPO} ${PFIX} {}" ::: ${TODO};
} \
|| {
    for f in ${TODO}; do
        build ${REPO} ${PFIX} ${f};
    done
}

